package l2r.gameserver.model.entity.olympiad;

/**
 * @author GodFather
 */
public enum BattleStatus
{
	BEGIN,
	TELEPORT_TO_ARENA,
	GAME_STARTED,
	BATTLE_COUNTDOWN_FIRST,
	BATTLE_COUNTDOWN_SECOND,
	BATTLE_STARTED,
	BATTLE_IN_PROGRESS,
	GAME_CANCELLED,
	GAME_STOPPED,
	TELEPORT_TO_TOWN,
	CLEANUP,
	IDLE
}